[package]
name = "common"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = true, features = [] }
tracing = { version = "0.1", default-features = true, features = [] }
tracing-subscriber = { version = "0.3", default-features = true, features = [] }
