name: Linux
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: linux-ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Lint
        uses: m3y/rust-just-action@v1
        with:
          command: lint

      - name: Proto generation succeeds
        uses: m3y/rust-just-action@v1
        with:
          command: genproto

      - name: Test
        uses: m3y/rust-just-action@v1
        with:
          command: test

      - name: Build Debug
        uses: m3y/rust-just-action@v1
        with:
          command: test

      - name: Build Release
        uses: m3y/rust-just-action@v1
        with:
          command: test

      - name: Bench
        uses: m3y/rust-just-action@v1
        with:
          command: bench
